# Generated by Django 5.2.7 on 2025-10-27 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorActuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Датчик–Привод',
                'verbose_name_plural': 'Датчики–Приводы',
            },
        ),
        migrations.AlterModelOptions(
            name='actuator',
            options={'verbose_name': 'Привод', 'verbose_name_plural': 'Приводы'},
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Сигнал тревоги', 'verbose_name_plural': 'Сигналы тревоги'},
        ),
        migrations.AlterModelOptions(
            name='command',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='commandarg',
            options={'verbose_name': 'Команда-Аргумент', 'verbose_name_plural': 'Команды-Аргументы'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Постройка', 'verbose_name_plural': 'Постройки'},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'verbose_name': 'Правило', 'verbose_name_plural': 'Правила'},
        ),
        migrations.AlterModelOptions(
            name='rulesensor',
            options={'verbose_name': 'Правило-Сенсор', 'verbose_name_plural': 'Правила-Сенсоры'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Датчик', 'verbose_name_plural': 'Датчики'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Единица изменения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AddField(
            model_name='actuator',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='core.facility'),
        ),
        migrations.AlterField(
            model_name='actuator',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.sensor'),
        ),
        migrations.AddIndex(
            model_name='actuator',
            index=models.Index(fields=['facility'], name='core_actuat_facilit_945378_idx'),
        ),
        migrations.AddField(
            model_name='sensoractuator',
            name='actuator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actuator'),
        ),
        migrations.AddField(
            model_name='sensoractuator',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='actuators',
            field=models.ManyToManyField(blank=True, related_name='sensors', through='core.SensorActuator', to='core.actuator'),
        ),
        migrations.AddIndex(
            model_name='sensoractuator',
            index=models.Index(fields=['sensor'], name='core_sensor_sensor__d86eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='sensoractuator',
            index=models.Index(fields=['actuator'], name='core_sensor_actuato_94ab5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sensoractuator',
            unique_together={('sensor', 'actuator')},
        ),
    ]
