# Generated by Django 5.2.7 on 2025-10-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backfill_actuator_links'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='actuator',
            name='core_actuat_sensor__1cd4d4_idx',
        ),
        migrations.RemoveField(
            model_name='actuator',
            name='sensor',
        ),
    ]
