# Generated by Django 5.2.7 on 2025-10-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_actuator_core_actuat_sensor__1cd4d4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.command')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rule')),
            ],
            options={
                'verbose_name': 'Правило-Команда',
                'verbose_name_plural': 'Правила-Команды',
                'indexes': [models.Index(fields=['command'], name='core_ruleco_command_dffe9f_idx')],
                'unique_together': {('rule', 'command')},
            },
        ),
    ]
