# Generated by Django 5.2.7 on 2025-10-27 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rulecommand'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='core_alert_sensor__9b1cbc_idx',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='sensor',
        ),
    ]
