# Generated by Django 5.2.7 on 2025-10-27 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_alert_core_alert_sensor__9b1cbc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commandarg',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commandarg',
            name='command',
        ),
        migrations.RemoveIndex(
            model_name='command',
            name='core_comman_issued__79da88_idx',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='issued_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='command',
            old_name='issued_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='command',
            name='command',
        ),
        migrations.RemoveField(
            model_name='command',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='command',
            name='error',
        ),
        migrations.AddField(
            model_name='command',
            name='commands_args',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('inprogress', 'Inprogress')], default='free', max_length=16),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['created_by'], name='core_comman_created_2cae0b_idx'),
        ),
        migrations.DeleteModel(
            name='CommandArg',
        ),
    ]
