# Generated by Django 5.2.7 on 2025-10-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_commandarg_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
