# Generated by Django 5.2.7 on 2025-10-28 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_actuator_is_active_sensor_is_active'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='core_alert_state_61ab90_idx',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='ack_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='ack_by',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='state',
        ),
    ]
