# Generated by Django 5.2.7 on 2025-10-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_alert_core_alert_state_61ab90_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='current_value',
            field=models.FloatField(default=0),
        ),
    ]
