# Generated by Django 5.2.7 on 2025-10-15 06:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Уникальный код/серийник устройства', max_length=64, verbose_name='Идентификатор')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Название')),
                ('metric', models.CharField(choices=[('temperature', 'Температура'), ('humidity', 'Влажность'), ('soil', 'Влажность почвы'), ('co2', 'CO₂'), ('pressure', 'Давление'), ('light', 'Освещённость'), ('other', 'Другое')], max_length=32, verbose_name='Измеряемая величина')),
                ('unit', models.CharField(blank=True, help_text='Напр. °C, %, ppm, lx', max_length=16, verbose_name='Единица измерения')),
                ('location', models.CharField(blank=True, max_length=128, verbose_name='Локация/зона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время измерения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor', verbose_name='Датчик')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['owner', 'metric'], name='sensors_sen_owner_i_8d7c13_idx'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('owner', 'identifier'), name='unique_sensor_per_owner'),
        ),
        migrations.AddIndex(
            model_name='reading',
            index=models.Index(fields=['sensor', 'measured_at'], name='sensors_rea_sensor__7e562a_idx'),
        ),
    ]
