# Generated by Django 5.2.7 on 2025-10-15 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('min_val', models.FloatField(blank=True, null=True)),
                ('max_val', models.FloatField(blank=True, null=True)),
                ('sampling_s', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, db_column='unit_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='sensors.unit')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
                'db_table': 'sensors',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(db_column='sensor_id', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
                'db_table': 'readings',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['ts'], name='readings_ts_idx'), models.Index(fields=['sensor', 'ts'], name='readings_sensor_ts_idx')],
                'constraints': [models.UniqueConstraint(fields=('sensor', 'ts'), name='unique_reading_per_sensor_ts')],
            },
        ),
        migrations.AddIndex(
            model_name='sensor',
            index=models.Index(fields=['user'], name='sensors_user_idx'),
        ),
    ]
