# Generated by Django 5.2.7 on 2025-10-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='identifier',
            field=models.CharField(max_length=64, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=16, verbose_name='Единица измерения'),
        ),
    ]
